# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, pull_request]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "site"
  site:
    name: SITE
    # The type of runner that the job will run on Windows 2019
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: |
        download_url="https://usysdev.github.io/jdk/java-1.8.0-openjdk-1.8.0.292-2.b10.dev.redhat.windows.x86_64.zip"
        wget -O $RUNNER_TEMP/java_package.zip $download_url
      - uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '8'
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Runs a single command using the runners shell
      - name: Site with Maven
        run: mvn --batch-mode clean site --file pom.xml

      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: target/site/
